apiVersion: v1
kind: Service
metadata: 
  name: redis
  labels:
    name: redis-service
    app: domo-voting-app
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: domo-voting-app